name: EventManager
version: '0.0.1'
main: com.eventManager.EventManager
api-version: '1.21'
authors: [ MrArt_SN ]
description: Плагин для создания случайных событий с сундуками и лутом

commands:
  event:
    description: Управление событиями
    usage: /event <start|stop|restart|info|reload>
    permission: eventmanager.admin
    permission-message: У вас нет прав для использования этой команды!

permissions:
  eventmanager.admin:
    description: Доступ к командам управления событиями
    default: op
